version: "3"
services:
  influxdb:
    image: "influxdb:1.7-alpine"
    ports:
    - "8086:8086"
    - "8083:8083"
    - "2003:2003"
    volumes:
    - /home/martin/Projects/trading_bot/playground/influxdb:/var/lib/influxdb
